version: '3.8'
services:
  url-svc:
    build:
      context: .
      dockerfile: Dockerfile.runtime
    image: url-shortener-deploy
    container_name: url-svc-prod
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/urlshortener
  mongo:
    image: mongo:4.2.1
    hostname: mongo
    restart: always